name: deploy to ec2
on:
    workflow:
        workflow: ['Docker Image CI']
             type: completed
jobs:
    deploy:
        runs-on: ubuntu-latest 
        steps:
            - name: deploy to ec2
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.EC2_HOSt}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_KEY}}
                scrpit:
                    docker pull workdevharsh/nodeapp:latest
                    docker run -f nodeapp || true
                    docker rm nodeapp || true
                    docker run -d --name nodeapp -p 80:3000 workdevharsh/
                    nodeapp:latest