name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login to Dockerhub
      uses: actions/checkout@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        token   : ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      run: docker buiold -t workdevharsh/nodeapp:latest .
    - name: push docker image in docker hub
      run: docker push workdevharsh/nodeapp:latest
